name: cloudipsp_mobile
description: Cloudipsp SDK for Mobile(Android, iOS). The only way to accept payment with Fondy service on Flutter platform for mobiles.
version: 0.2.1
homepage: https://github.com/cloudipsp/flutter-mobile-sdk
repository: https://github.com/cloudipsp/flutter-mobile-sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: "^2.0.10"
  http: "^0.13.3"
  email_validator: "^2.0.1"

dev_dependencies:
  build_runner: ^2.1.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.cloudipsp.mobile
        pluginClass: CloudipspMobilePlugin
      ios:
        pluginClass: CloudipspMobilePlugin
