name: cloudipsp_mobile
description: Cloudipsp SDK for Mobile(Android, iOS). The only way to accept payment with Fondy service on Flutter platform for mobiles.
version: 0.4.1
homepage: https://github.com/cloudipsp/flutter-mobile-sdk
repository: https://github.com/cloudipsp/flutter-mobile-sdk

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.3.9"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: "^4.2.0"
  http: "^0.13.6"
  email_validator: "^2.1.17"

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.cloudipsp.mobile
        pluginClass: CloudipspMobilePlugin
      ios:
        pluginClass: CloudipspMobilePlugin
